# Generated by Django 5.2.3 on 2025-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_resumetemplate_customuser_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='is_latex_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='latex_styles',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='template_type',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('professional', 'Professional'), ('ats_friendly', 'ATS Friendly'), ('latex', 'LaTeX')], max_length=20),
        ),
    ]
